import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
  title: 'Stock App',
  description: 'Generated by metafar',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='header'>
          <h2 className='title'>Stocks</h2>
        </header>
        <main className='main'>
        {children}
        </main>
        <footer className='footer'>
          <p className='copyright'>©2023 metafar - All rights reserved</p>
        </footer>
      </body>
    </html>
  )
}
